Repository found-pleiade/dionysos-client, pull requests merged in 2022-07, with the labels that each got.

#15 14 keypress now being deprecated it need to be replaced by keydown
  src/components/Button.tsx
  src/components/ChangeUsernameModal.tsx
  src/components/Id.tsx
  src/components/Input.tsx
  src/components/RoomInputGroup.tsx
  src/pages/connect.tsx
  src/tests/Button.test.tsx
Labels: bug, enhancement

#19 3 fix id copy paste on all systems
  src/components/Id.tsx
  src/utils/index.tsx
Labels: bug, good first issue

#25 Add README entries for tests
  README.md
Labels: documentation

#28 Remove unused code
  src/App.tsx
  src/components/ChangeUsernameModal.tsx
  src/components/Help.tsx
  src/components/Id.tsx
  src/components/Input.tsx
  src/components/JoinRequestModal.tsx
  src/components/Message.tsx
  src/components/Messages.tsx
  src/components/Modal.tsx
  src/components/OverlayMenu.tsx
  src/components/RoomDisplay.tsx
  src/components/RoomInputGroup.tsx
  src/components/Separator.tsx
  src/components/UserDisplay.tsx
  src/components/Userlist.tsx
  src/components/Videojs.tsx
  src/components/WebSocketModal.tsx
  src/constants/index.tsx
  src/hooks/connection.ts
  src/hooks/help.ts
  src/hooks/inputStatusIcon.tsx
  src/hooks/joinRequests.ts
  src/hooks/messages.ts
  src/hooks/modal.ts
  src/hooks/room.ts
  src/hooks/users.ts
  src/hooks/version.ts
  src/pages/home.tsx
  src/pages/register.tsx
  src/tests/Help.test.tsx
  src/tests/utils.test.tsx
  src/utils/index.tsx
  src/utils/types.ts
Labels: enhancement

#20 Create eslint.yml
  .github/workflows/eslint.yml
Labels: documentation

#32 Remove unecessary triple `
  README.md
Labels: documentation

#31 Add NodeJS version to the README
  README.md
Labels: documentation

#33 29 put most of whats in indexcss in the tailwind config file
  src/components/Input.tsx
  src/index.css
Labels: enhancement

#30 23 store the server address somewhere
  .eslintrc.js
  src/components/Input.tsx
  src/components/register/ErrorCard.tsx
  src/components/register/ServerModal.tsx
  src/hooks/register.ts
  src/hooks/settings.ts
  src/hooks/version.ts
  tailwind.config.js
Labels: enhancement

#41 40 fix major architecture problem
  src/App.tsx
  src/components/Input.tsx
  src/components/register/ServerModal.tsx
  src/contexts/SettingContext.ts
  src/hooks/register.ts
  src/hooks/settings.ts
  src/hooks/version.ts
Labels: bug, enhancement

#37 36 style centercard for dark theme
  src/components/register/CenterCard.tsx
  src/pages/register.tsx
Labels: enhancement

#43 Rename username to name
  src/components/register/RegisterForm.tsx
  src/hooks/register.ts
Labels: api change

#44 Add the class only on success
  src/components/register/ServerModal.tsx
Labels: bug

#45 38 store the user id and username in a user hook
  src/App.tsx
  src/components/register/RegisterForm.tsx
  src/contexts/UserContext.ts
  src/hooks/createUser.ts
  src/hooks/getUser.ts
  src/hooks/settings.ts
  src/hooks/user.ts
Labels: enhancement, api change

#49 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#53 52 show the username in the homes panel
  src/components/home/MinimizeIcon.tsx
  src/components/home/OverlayMenu.tsx
  src/components/home/Panel.tsx
  src/components/home/UserDisplay.tsx
  src/pages/home.tsx
Labels: enhancement

#48 Reorganize and upgrade the README
  README.md
Labels: documentation

#56 54 add a modal to rename the user
  src/components/Button.tsx
  src/components/ErrorCard.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/ServerModal.tsx
  src/hooks/renameUser.ts
  src/hooks/user.ts
  src/pages/home.tsx
Labels: enhancement

#62 Add editor config for vscode
  .gitignore
  .vscode/settings.json
Labels: enhancement

#64 Remove trailing / at the end of urls
  src/hooks/createUser.ts
  src/hooks/renameUser.ts
Labels: api change

#68 65 create top panel form for creating and joining rooms
  src/contexts/RoomContext.ts
  src/hooks/room.ts
  src/hooks/settings.ts
  src/hooks/user.ts
Labels: enhancement

#70 69 move the app to a website
  .github/workflows/test-on-pr.yml
  package.json
  pnpm-lock.yaml
  src-tauri/.gitignore
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/build.rs
  src-tauri/icons/128x128.png
  src-tauri/icons/128x128@2x.png
  src-tauri/icons/32x32.png
  src-tauri/icons/Square107x107Logo.png
  src-tauri/icons/Square142x142Logo.png
  src-tauri/icons/Square150x150Logo.png
  src-tauri/icons/Square284x284Logo.png
  src-tauri/icons/Square30x30Logo.png
  src-tauri/icons/Square310x310Logo.png
  src-tauri/icons/Square44x44Logo.png
  src-tauri/icons/Square71x71Logo.png
  src-tauri/icons/Square89x89Logo.png
  src-tauri/icons/StoreLogo.png
  src-tauri/icons/icon.icns
  src-tauri/icons/icon.ico
  src-tauri/icons/icon.png
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
Labels: enhancement

#71 Fix url
  src/hooks/settings.ts
Labels: api change

#75 74 update the readme as tauri is gone
  README.md
Labels: documentation

#73 Remove json parser for renameUser
  src/hooks/renameUser.ts
Labels: api change

#82 79 remove eslint preset
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/eslint.yml
  .github/workflows/test-on-pr.yml
  .prettierignore
  .prettierrc.json
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Button.tsx
  src/components/ErrorCard.tsx
  src/components/Input.tsx
  src/components/RowGroup.tsx
  src/components/SpaceBetween.tsx
  src/components/home/MinimizeIcon.tsx
  src/components/home/OverlayMenu.tsx
  src/components/home/Panel.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/CenterCard.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/ServerModal.tsx
  src/contexts/RoomContext.ts
  src/contexts/SettingContext.ts
  src/contexts/UserContext.ts
  src/hooks/createUser.ts
  src/hooks/getUser.ts
  src/hooks/renameUser.ts
  src/hooks/room.ts
  src/hooks/settings.ts
  src/hooks/sideMenu.ts
  src/hooks/user.ts
  src/hooks/version.ts
  src/index.css
  src/main.tsx
  src/pages/home.tsx
  src/pages/register.tsx
  src/tests/Button.test.tsx
  src/tests/utils.test.tsx
  src/utils/index.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: enhancement

#80 76 reorganize the files
  src/App.tsx
  src/components/Button.test.tsx
  src/components/home/OverlayMenu.tsx
  src/components/home/Panel.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/ServerModal.tsx
  src/contexts/RoomContext.ts
  src/contexts/SettingContext.ts
  src/contexts/UserContext.ts
  src/layouts/RowGroup.tsx
  src/layouts/SpaceBetween.tsx
  src/pages/home.tsx
  src/pages/register.tsx
  src/states/getVersion.ts
  src/states/room.ts
  src/states/settings.ts
  src/states/sideMenu.ts
  src/states/user/createUser.ts
  src/states/user/getUser.ts
  src/states/user/index.ts
  src/states/user/renameUser.ts
  src/utils/index.test.tsx
Labels: enhancement

#83 81 in test on pr only tsc rather than building
  .github/workflows/test-on-pr.yml
Labels: enhancement

#84 77 disable next button if connection isnt possible
  src/components/register/RegisterForm.tsx
  src/utils/index.test.tsx
  src/utils/index.tsx
Labels: enhancement

#85 78 check for generics instead of throwing error in reducers
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/ServerModal.tsx
  src/states/room.ts
  src/states/settings.ts
  src/states/user/index.ts
Labels: enhancement
