Repository found-pleiade/dionysos-client, pull requests merged in 2022-08, with the labels that each got.

#87 86 implement authentication and authorization on certain routes
  src/App.tsx
  src/components/register/RegisterForm.tsx
  src/features/auth.ts
  src/states/user/getUser.ts
  src/states/user/renameUser.ts
Labels: enhancement, api change

#91 89 add a reset button for the server modal
  src/components/register/ServerModal.tsx
  src/states/settings.ts
Labels: enhancement

#95 92 allow to create a room and a sharable url
  src/App.tsx
  src/components/home/CreateRoom.tsx
  src/features/shareRoom.ts
  src/pages/home.tsx
  src/pages/register.tsx
  src/states/room/createRoom.ts
  src/states/room/index.ts
  src/states/room/joinRoom.ts
Labels: enhancement

#100 Change the server address
  src/states/settings.ts
Labels: enhancement

#101 94 remove vscodesettings from repo and add it to gitignore
  .gitignore
  .vscode/settings.json
Labels: bug

#103 Fix button style for all states
  src/components/Button.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/ServerModal.tsx
Labels: bug

#104 Remove every safeMutate
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/states/user/createUser.ts
  src/states/user/renameUser.ts
Labels: enhancement

#106 Remove setServerAddressBackup from reset
  src/components/register/ServerModal.tsx
Labels: bug

#107 88 trigger the delete route for the user when the customer exits the website
  src/pages/home.tsx
  src/states/user/deleteUser.ts
Labels: enhancement

#108 90 add animations to error messages in modals
  src/components/ErrorCard.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/ServerModal.tsx
Labels: enhancement

#111 Add name validation and errors to rename modals
  src/components/home/UserDisplay.tsx
Labels: enhancement

#112 22 add an input helper
  src/components/register/RegisterForm.tsx
Labels: enhancement

#115 114 run prettier on the project
  .prettierignore
  src/components/Button.test.tsx
  src/components/home/OverlayMenu.tsx
  src/components/home/Panel.tsx
  src/features/auth.ts
  src/features/shareRoom.ts
  src/states/getVersion.ts
  src/states/room/createRoom.ts
  src/states/room/joinRoom.ts
  src/states/user/createUser.ts
Labels: prettier

#116 98 accept minor version mismatch
  src/components/register/ServerModal.tsx
  src/features/version.ts
  src/pages/register.tsx
  src/states/getVersion.ts
Labels: bug, refactor

#122 119 change app state on click rather than typing url renaming
  src/components/home/UserDisplay.tsx
  src/components/register/ServerModal.tsx
  src/features/version.ts
  src/states/user/renameUser.ts
Labels: api, refactor

#123 121 replace delete by disconnect
  src/components/home/CreateRoom.tsx
  src/features/shareRoom.ts
  src/pages/home.tsx
  src/states/room/createRoom.ts
  src/states/room/disconnectUser.ts
  src/states/room/index.ts
  src/states/room/joinRoom.ts
Labels: api, refactor

#128 Prettier
  src/features/version.ts
  src/states/room/createRoom.ts
  src/states/room/joinRoom.ts
Labels: prettier

#125 117 refactor the panel navigation
  src/components/home/MinimizeIcon.tsx
  src/components/home/Panel.tsx
Labels: refactor

#126 124 allow user to press enter to validate inputs
  src/components/Button.tsx
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/ServerModal.tsx
Labels: feature

#132 131 pre commit prettier and test modified files only
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: feature

#133 97 move create room button to a modal 1
  src/components/home/CreateRoom.tsx
  src/pages/home.tsx
  src/states/sideMenu.ts
Labels: feature

#138 Add share button to other users
  src/pages/home.tsx
Labels: feature

#139 Remove classes about dialog width
  src/pages/home.tsx
Labels: feature

#140 137 show the copy state in the UI
  src/pages/home.tsx
Labels: bug, feature

#143 141 remove local state of server side data
  src/components/home/UserDisplay.tsx
  src/components/register/RegisterForm.tsx
  src/pages/home.tsx
  src/states/room/createRoom.ts
  src/states/room/joinRoom.ts
  src/states/user/index.ts
  src/states/user/renameUser.ts
Labels: refactor

#149 Add an icon next to the name
  src/components/home/UserDisplay.tsx
Labels: feature

#150 145 fix buttons hover overrighting the success color
  src/components/Button.tsx
Labels: bug

#153 Add pretty quick staged option
  .husky/pre-commit
Labels: bug

#151 142 add a button to close the modal
  src/pages/home.tsx
Labels: bug, feature

#155 Change default server URL
  src/states/settings.ts
Labels: api

#157 🇫🇷
  src/states/settings.ts
Labels: api
